### PR TITLE
Export only selected nodes

### PR DESCRIPTION
**Pull request by ochounos**
Also only materials associated to such nodes are exported.

### CODE REVIEW

**Comment by feedbackex** [comment]
Hi @ochounos, Thank you for your attention, but there is a few problem for your code:

- There is inconsistent other codes which use get_export_nodes functions.
- Exporting error messages for unselected nodes.

I guess I go on wıth another code which is more comprehensible and improvable.
Also you do not need to change __get_materials functions
for group in utils.get_export_nodes(self.__config.export_selected_nodes):  line meets associated material exports.

**Comment by ochounos** [comment]
Feel fre to propose any other code and reuse any code that I have posted.

**Comment by dwhite4** [comment]
@ochounos, I think we should work with @feedbackex pull request for exporting selected nodes since it has no merge conflicts.  Feel free to make any commits you see fit to that pull request and we can close this one.

**Comment by ochounos** [comment]
This implementation has some problems as @feedbackex addressed. If I found some problem in the other implementation I will add a new pull request and not use this pull request. You did right closing this one. Thanks.

**Comment by dwhite4** [comment]
Sounds good!

**Pull request closed without merging**
