### PR TITLE
Fix add branch joint

### PR DESCRIPTION
**Pull request by ochounos**
Obtaining the new name for the new joint was not working properly, was missing to compare with the current branch.

### CODE REVIEW

**Comment by feedbackex** [comment]
Reviewed.

**Comment by ochounos** [comment]
I found that maybe there is sequence not working, i.e. assigning highest values for branch2_3, being 2 and 3, but then found branch3_2, so highest branch is 3 but still keep highest joint 3, which is wrong. I'm trying to fix this case and I will push changes again to this pull request.

**Comment by ochounos** [comment]
Ok, commited changes to manage latest case. Please review again.

**Comment by dwhite4** [comment]
At the end of the function you have these lines:

'''python
    if (highest_branch_number != 0):
        if (is_new_branch):
            return "branch{}_1".format(highest_branch_number + 1)
        else:
            return "branch{}_{}".format(
                    highest_branch_number, highest_joint_number + 1)
'''

But 'highest_join_number is a dictionary.'

**Comment by ochounos** [comment]
You are right, I had some problems merging both commits, I had this in my original code when tested. Let me try to merge again.

**Comment by ochounos** [comment]
Ok, now is done, sorry, try again.

**Comment by dwhite4** [comment]
No problem, looks good

**Pull request merged**
