### PR TITLE
Cryblend 5.1 Release

### PR DESCRIPTION
**Pull request by feedbackex**
cryblendlogo_51_second_pose

#### Compatibility:
* Only compatible with CryEngine 3.5 and up.
* Only compatible with Blender 2.7 and up.
* Supports primary assets: CGF, CGA, CHR, SKIN, ANM, I_CAF.
* Compatible with LumberYard.

#### UI Changes:
* Apply Scale Animation.
* Edit Inverse Kinematics panel in Bone Utilities.
* Do materials and fix weight default were set to false in export menu.
* Add Property is changed with User Defined Properties menu.
* Same options in quick menu, left tab panel and main menu.

#### New Features:
* Skeleton Physic.
* New Inverse Kinematics Bone Panel in Bone Utilities.
* Cycles render material support.
* Completely new interactive User Defined Property system.
* Added apply rotation and scale for skeleton that have animation without break bone.
* Delete .animsettings, .caf, .$animsettings files if there are exist for clean reexport animation.
* Set main material name which show in cryengine.
* Change selected material physic in Do Material panel.
* More material notation formats supported.
* New material management options.
* Proxies improvement.
* Export only selected nodes.
* Game folder selection to better management of textures.
* Remove unused vertex groups option.

#### Improvements/Fixes:
* Texture export fix.
* Skeleton Animation.
* Blender 2.74 and up Skeleton and Animation support.
* Now bone names replace double underscore with whitespace like maya.
* CGF file is processed one time by rc.
* Proxies problems.
* Faster skin export.
* More than 8 bones per vertex fix.
* Residual vertex groups in skins generating problems.
* Problem creating few branches in touch bending.

### CODE REVIEW

**Comment by feedbackex** [comment]
Hi guys, We late 3 months, I guess we must finally release that version. 
Bugs and feature may be go on for milestone 6.0.
I plan to merge Cryblend 5.1 Release to master at 00:00 15 May 2016.

I will announce it on cryblend facebook page.

Also, I have added new branch named stable-5.0 for backward.

Thank you for all of your attentions.

Is there any problem?

**Comment by feedbackex** [comment]
### Finalize checking version:

__Checking Mesh Exporting__

- [ ] Mesh exporting.
- [ ] Multiple mesh exporting.
- [ ] Only selected mesh exporting.

-----------------------------------------------------------------------

__Checking Skeleton and Animation__

- [ ] Skeleton exporting.
- [ ] Skeleton physic exporting.
- [ ] Bone inverse kinematics exporting.
- [ ] Animation exporting.
- [ ] Multiple skin exporting.

-----------------------------------------------------------------------

__Material and Textures__

- [ ] Do materials with classic method.
- [ ] Do materials with auto name.
- [ ] Texture exporting.
- [ ] Do textures.
- [ ] Physic exporting.

-------------------------------------------------------------------------

__Clean up__

- [ ] Trim trailing spaces from codes when complete checking.

**Comment by feedbackex** [comment]
A new image has been created for Cryblend 5.1 and announced release at facebook page.

**Comment by dwhite4** [comment]
@feedbackex 

You can use autopep8 to quickly make sure all the code fits the python standards (includes removing of trailing spaces) before you release.

Example:
cd C:\Users\Dan\Documents\GitHub\CryBlend\io_export_cryblend
autopep8 --in-place --aggressive --aggressive __init__.py add.py configuration.py desc.py exceptions.py export.py outpipe.py rc.py utils.py

**Comment by feedbackex** [comment]
Thank you for nicely tip @dwhite4, I will perform it end of checking.

**Comment by feedbackex** [comment]
- Checking stages have been completed successfully.
- Pep 8 convention have been applied.

Thank you guys all of your attention.
I am going to merge release after 2 hours, at 00:00 GMT 15 May 2016.

**Pull request merged**
